#!/bin/bash

IMG_PATH=/home/lucas/Images/scrot/
EDIT=kolourpaint


prog="
1.xclip_fullscreen
2.save_fullscreen
3.xclip_section
4.save_section
5.edit_fullscreen
6.edit_selection
"

cmd=$(dmenu  -l 20  -p 'Screen Shot'   <<< "$prog")

cd $IMG_PATH
case ${cmd%% *} in
	1.xclip_fullscreen)	import -window root foo.png && xclip -selection clipboard -t image/png -i foo.png && rm foo.png ;;
	2.save_fullscreen)	import -window root "$(date '+%F_%H-%M-%S').png" ;;
	3.xclip_section)	import foo.png && xclip -selection clipboard -t image/png -i foo.png && rm foo.png ;;
	4.save_section)	import "$(date '+%F_%H-%M-%S').png" ;;
  	*)		exec "'${cmd}'"  ;;
esac

