#!/bin/bash

file=$1
base="${file%.*}"
extension=${file##*.}
SCRIPT=$(readlink -f "$1")
SCRIPTPATH=$(dirname "$SCRIPT")

if [ ${extension} = "c" ] || [ ${extension} = "C" ]
then
  clang ${file} -o ${base} && $SCRIPTPATH/${base}
elif [ ${extension} = "cpp" ] || [ ${extension} = "hpp" ]
then
  (cd $SCRIPTPATH && make) || (cd $SCRIPTPATH/../ && make) || (cd $SCRIPTPATH/../../ && make) || (cd $SCRIPTPATH/../../../ && make)
#  $(clang++ -std=c++20 $SCRIPTPATH/*.cpp $SCRIPTPATH/*/*.cpp -o $SCRIPTPATH/../main || clang++ -std=c++20 $SCRIPTPATH/../*.cpp $SCRIPTPATH/../*/*.cpp)
#  && $($SCRIPTPATH/../main || $SCRIPTPATH/../../main)
elif [ ${extension} = "m" ]
then
  octave $SCRIPTPATH/${file}
fi
